### ISSUE TITLE
Discussion: Support of the Standard Relayer API (Contract Addresses vs. Symbols)

### ISSUE THREAD

**Issue by stefanmendoza** [perich/ethereum-dex-prices-service#2]
While skimming through the available 0x relayers to get a better idea of what exchanges may be possible to be supported, I noticed that the 0x schema for order books actually returns asks and bids in terms of the maker and taker address, not by the resolved symbol. Example:
https://github.com/0xProject/standard-relayer-api/blob/master/http/v2.md#get-v2orderbook

Are there plans to support exchanges that use the 0x SRA? This would require the ability to pass in a contract address as an alternative to a symbol. On a similar note, it raises the question of asset resolution. For example, if a user passes `ABC`, there currently aren't any checks to ensure that `ABC` actually corresponds to the same assets. Given the goal of supporting any asset on any exchange, I see a couple paths off the top of my head:

**1a)** For major exchanges, keep a hard-coded mapping of symbol -> contract address if it's easily identifiable (ZRX, AST, BNB, etc.)
**1b)** Only support exchanges that provide tokens included in the "supported assets" mapping
**2)** Only support exchanges that allow retrieval of order books with contract addresses

And the potential issues:

**1a)** This obviously has a scaling problem and also brings up issues if contracts are redeployed
**1b)** This limits the amount of exchanges and assets available unless they're manually maintained in 1a
**2)** This allows for more flexibility in the sense that I could provide any address and if it shows up in an exchange we know that it's the same asset across exchanges but it limits consumers to knowing the address for the token contract, which they may not. Similar to 1b, this limits the amount of exchanges that could be supported.

Just some things that crossed my mind while looking around. Interested to get some feedback. :)

**Comment by grahamperich** [comment]
I agree that we should add support for the Standard Relayer API. Once we do that we could remove Radar Relay. And, in the future we'd never have to implement a new DEX if they were only sourcing liquidity from the Standard Relayer API.

I see two viable ways that we could add support:

1) Refactor the `main()` routine to accept either a token symbol OR a token address. We could crawl the metadata of the token on the blockchain to derive the symbol, and then use that symbol with the existing code to get a result. This is probably the most straightforward option, but the downside is that the service becomes less predictable. Specifically, the schema of the result JSON would vary based on whether you searched with a token address or a symbol. This is because in the case that a user enters a symbol, the code would have no choice but to skip over the Standard Relayer API and omit it from the results.

2) Instead of changing the semantics, we could build an abstraction. We would need comprehensive token metadata data for this approach. For example, if we had a list of the top tokens by market cap and a mapping to their contract addresses, then the data would be more consistent and more reliable

I would merge a PR for either one of these, and I will probably pursue number 2 myself eventually if no one else has built it.

**Comment by CruiseMan** [comment]
@grahamperich CMC provides this kind of mapping `https://pro-api.coinmarketcap.com/v1/cryptocurrency/map?CMC_PRO_API_KEY=XXX&limit=1`
```json
{
    "status": {
        "timestamp": "2019-02-01T03:58:51.050Z",
        "error_code": 0,
        "error_message": null,
        "elapsed": 8,
        "credit_count": 1
    },
    "data": [
                {
            "id": 1839,
            "name": "Binance Coin",
            "symbol": "BNB",
            "slug": "binance-coin",
            "is_active": 1,
            "first_historical_data": "2017-07-25T04:30:05.000Z",
            "last_historical_data": "2019-02-01T03:54:02.000Z",
            "platform": {
                "id": 1027,
                "name": "Ethereum",
                "symbol": "ETH",
                "slug": "ethereum",
                "token_address": "0xB8c77482e45F1F44dE1745F52C74426C631bDD52"
            }
        }
    ]
}
```

**Comment by stefanmendoza** [comment]
@grahamperich are you going to setup the config pattern for API keys when you implement the CoinMarketCap stuff?

**Comment by grahamperich** [comment]
I don't think so.. adding support for exchanges that require an API key is out of scope for implementing the standard relayer.

**Comment by stefanmendoza** [comment]
@grahamperich I was more thinking if you establish the pattern of retrieving the API key for CoinMarketCap, wouldn't we just want to follow the same pattern for storing and retrieving other API keys that could be used in the service?

**Comment by tmlee** [comment]
@grahamperich 
If you are looking to retrieve contract address, you may try our CoinGecko API which requires no key

For instance https://api.coingecko.com/api/v3/coins/0x, you will be able to access the contract address
Full docs at https://www.coingecko.com/api

Let me know what you make of that and happy to answer any questions

**Comment by grahamperich** [comment]
thanks @tmlee .. I'll check it out! Looks like a good fit

**Comment by tmlee** [comment]
@grahamperich No problem, let me know if you have any questions! This is a well built library, been testing out a few queries here and there. 👍 👍 👍

**Comment by perich** [comment]
@tmlee @stefanmendoza  I integrated the CoinGecko API in this PR https://github.com/perich/ethereum-dex-prices-service/pull/33
